version: "3.8"

services:
  postgres:
    image: postgres:10
    container_name: local_postgres10
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo_db
    ports:
      - "35432:5432"  # наружу пробрасываем 55432
    volumes:
      - pg_data10:/var/lib/postgresql/data

volumes:
  pg_data10:

